[package]
name = "funkcje"
version = "0.1.0"
authors = ["TomaszPielecki <74858305+TomaszPielecki@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
